import { test, expect, type Page } from '@playwright/test'
async function apiPost(page: Page, path: string, body: unknown = {}) {
  return page.evaluate(async ({path,body}) => {
    const {token} = await (await fetch('/api/bootstrap')).json()
    const response = await fetch(`/api${path}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)})
    if (!response.ok) throw new Error(`${path}: ${await response.text()}`)
    return response.json()
  },{path,body})
}
async function state(page: Page) {
  return page.evaluate(async () => { const {token} = await (await fetch('/api/bootstrap')).json(); return (await fetch('/api/state',{headers:{Authorization:`Bearer ${token}`}})).json() })
}
async function connectPractice(page: Page) {
  await page.getByText('连接选项与本地练习',{exact:true}).click()
  await page.getByTestId('practice-start').click()
  await expect(page.getByTestId('practice-select')).toBeEnabled()
  await page.getByTestId('practice-select').click()
  await page.getByTestId('connect').click()
  await expect(page.getByTestId('send-once')).toBeEnabled()
}
test.beforeEach(async ({page}) => {
  page.on('dialog',dialog => dialog.accept())
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'S10U TCP 调测工具台'})).toBeVisible()
  await apiPost(page,'/disconnect'); await apiPost(page,'/practice/stop')
  await expect(page.getByTestId('connect')).toBeEnabled()
})
test.afterEach(async ({page}) => { await apiPost(page,'/disconnect'); await apiPost(page,'/practice/stop') })
test('manual uplink sends once and refresh never reconnects or sends', async ({page}) => {
  await connectPractice(page)
  await page.getByTestId('preview').click()
  await expect(page.locator('.uplink-form [data-testid="packet-details"]')).toBeVisible()
  const before = await state(page)
  await page.getByTestId('send-once').click()
  await expect.poll(async () => (await state(page)).logs.filter((log: {direction:string;session_id:string}) => log.direction === 'tx' && log.session_id === before.connection.session_id).length).toBe(1)
  const session = (await state(page)).connection.session_id
  await page.reload()
  await expect(page.getByTestId('send-once')).toBeEnabled()
  const after = await state(page)
  expect(after.connection.session_id).toBe(session)
  expect(after.logs.filter((log: {direction:string;session_id:string}) => log.direction === 'tx' && log.session_id === session)).toHaveLength(1)
  await expect(page.getByTestId('environment-select').locator('input')).toBeDisabled()
})
test('raw unknown packet cannot be destructively backfilled', async ({page}) => {
  await page.getByText('原始 text / HEX',{exact:true}).click()
  const raw = '[3G*2016001000*0009*UNKNOWN,x]'
  await page.getByTestId('raw-input').fill(raw)
  await page.getByTestId('raw-backfill').click()
  await expect(page.getByText('存在未知、缺失或无法完整映射的字段，禁止反填；原始输入已保留，可直接使用 raw 发送。',{exact:true})).toBeVisible()
  await expect(page.getByTestId('raw-input')).toHaveValue(raw)
  await expect(page.locator('.uplink-form [data-testid="packet-text"]')).toContainText('UNKNOWN,x')
})
test('position fields cover repeated arrays and unknown status bits', async ({page}) => {
  await page.getByTestId('uplink-UD').click()
  const status = page.getByTestId('status-hex')
  await status.fill('80000000')
  await page.getByTestId('status-bit-0').click()
  await expect(status).toHaveValue('80000001')
  await page.getByText(/基站列表 bases/).click()
  const count = await page.getByRole('button',{name:/删除基站/}).count()
  await page.getByTestId('add-base').click()
  await expect(page.getByRole('button',{name:/删除基站/})).toHaveCount(count + 1)
  await page.getByRole('button',{name:`删除基站${count + 1}`,exact:true}).click()
  await expect(page.getByRole('button',{name:/删除基站/})).toHaveCount(count)
  await page.getByText(/Wi-Fi 列表 wifi/).click()
  const wifiCount = await page.getByRole('button',{name:/删除Wi-Fi/}).count()
  await page.getByTestId('add-wifi').click()
  await expect(page.getByRole('button',{name:/删除Wi-Fi/})).toHaveCount(wifiCount + 1)
  await page.getByText('固定',{exact:true}).click()
  await expect(page.getByTestId('field-date')).toBeEnabled()
})
test('SQLite environment saved in Chinese interface persists after refresh', async ({page}) => {
  await page.getByTestId('manage-config').click()
  const name = `本地回归环境-${Date.now()}`
  await page.getByTestId('saved-environment-name').fill(name)
  await page.getByTestId('save-environment').click()
  await expect(page.getByRole('cell',{name,exact:true})).toBeVisible()
  await page.reload()
  await page.getByTestId('manage-config').click()
  await expect(page.getByRole('cell',{name,exact:true})).toBeVisible()
})
test('anomalous raw bytes require explicit confirmation and cancel produces no send', async ({page}) => {
  await connectPractice(page)
  await page.getByText('原始 text / HEX',{exact:true}).click()
  const raw = '[3G*2016001000*0000*LK,0,0,85]'
  await page.getByTestId('raw-input').fill(raw)
  const session = (await state(page)).connection.session_id
  const txCount = async () => (await state(page)).logs.filter((log: {direction:string;session_id:string}) => log.direction === 'tx' && log.session_id === session).length
  const before = await txCount()
  await page.getByTestId('send-once').click()
  await expect(page.getByText('异常报文发送确认',{exact:true})).toBeVisible()
  expect(await txCount()).toBe(before)
  await page.getByRole('button',{name:'取消',exact:true}).click()
  expect(await txCount()).toBe(before)
  await page.getByTestId('send-once').click()
  await expect(page.getByText('异常报文发送确认',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'确认',exact:true}).click()
  await expect.poll(txCount).toBe(before + 1)
  await expect(page.locator('.uplink-form [data-testid="packet-text"]')).toHaveText(raw)
})
test('editing raw input during send leaves returned byte preview visibly stale', async ({page}) => {
  await connectPractice(page)
  const draft = await page.evaluate(async () => (await (await fetch('/api/bootstrap')).json()).metadata.defaults.LK)
  const packet = await apiPost(page,'/preview',{draft})
  await page.getByText('原始 text / HEX',{exact:true}).click()
  await page.getByTestId('raw-input').fill(packet.text)
  let release!: () => void
  const hold = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/send',async route => { const response = await route.fetch(); await hold; await route.fulfill({response}) })
  const request = page.waitForRequest('**/api/send')
  await page.getByTestId('send-once').click(); await request
  try { await page.getByTestId('raw-input').fill('[edited while sending]') } finally { release() }
  await expect(page.getByText('字段已修改，以下预览已过期；发送时会重新编码校验。',{exact:true})).toBeVisible()
  await expect(page.locator('.uplink-form [data-testid="packet-text"]')).toHaveText(packet.text)
  await expect(page.getByTestId('raw-input')).toHaveValue('[edited while sending]')
})
test('real TCP downlink manual reply and old-session send guard plus authenticated export', async ({page}) => {
  await apiPost(page,'/policies/VERNO',{mode:'manual',action:'normal',delay:0,version:'S10U-E2E',raw:'',raw_mode:'text'})
  await connectPractice(page)
  await page.getByRole('tab',{name:'下行接收与回复'}).click()
  await page.getByTestId('practice-command').click()
  await page.getByRole('option',{name:/VERNO/}).click()
  await page.getByTestId('practice-send').click()
  await expect(page.getByTestId('downlink-records').getByRole('row').filter({hasText:'VERNO'}).first()).toBeVisible()
  await page.getByTestId('downlink-records').getByRole('row').filter({hasText:'VERNO'}).last().click()
  await expect(page.getByTestId('reply-record')).toBeEnabled()
  await page.getByTestId('reply-record').click()
  await page.getByRole('button',{name:'确认',exact:true}).click()
  await expect(page.getByTestId('reply-record')).toBeDisabled()
  await page.getByTestId('practice-send').click()
  await expect.poll(async () => (await state(page)).downlinks.filter((r: {status:string;packet:{command:string}}) => r.packet.command === 'VERNO' && r.status === 'pending').length).toBeGreaterThan(0)
  await page.getByTestId('downlink-records').getByRole('row').filter({hasText:'待处理'}).last().click()
  await page.getByTestId('disconnect').click()
  await expect(page.getByTestId('reply-record')).toBeDisabled()
  await expect(page.getByTestId('connect')).toBeEnabled()
  await page.getByTestId('connect').click()
  await expect(page.getByText('这是旧会话接收记录，禁止向当前连接发送回复。',{exact:true})).toBeVisible()
  await expect(page.getByTestId('reply-record')).toBeDisabled()
  const downloadPromise = page.waitForEvent('download')
  await page.getByTestId('export-json').click()
  expect((await downloadPromise).suggestedFilename()).toMatch(/s10u-logs-.*\.json$/)
})
