# -*- coding: utf-8 -*-
"""报告模板多语言文案（zh-CN / en-US）。"""

STRINGS = {
    "zh-CN": {
        "report_info": "报告信息",
        "project": "项目",
        "report_kind": "报告类型",
        "coverage_period": "覆盖期",
        "tester": "测试人",
        "covered_modules": "覆盖模块",
        "generated_at": "生成时间",
        "sec_conclusion": "一、测试结论",
        "sec_metrics": "二、指标看板",
        "sec_key_issues": "三、重点问题",
        "sec_coverage": "四、功能测试范围与执行情况",
        "sec_module_detail": "五、模块明细",
        "sec_risk": "六、风险评估",
        "sec_lists": "七、未解决与待回归清单",
        "sec_appendix": "八、附录（解析详情 / 冲突 / 阈值）",
        "metrics_by_level": "按级别分布",
        "metrics_by_status": "按状态分布",
        "level": "级别",
        "count": "数量",
        "status": "状态",
        "total": "合计",
        "th_module": "测试模块",
        "th_core": "核心测试点",
        "th_priority": "优先级",
        "th_result": "结果状态",
        "th_open": "未关闭",
        "th_pending": "待回归",
        "th_deferred": "延期",
        "th_regfail": "回归不通过",
        "th_remark": "备注",
        "th_risk_dir": "风险方向（模块）",
        "th_risk_level": "风险等级",
        "th_action": "建议处置",
        "th_plan_area": "归属测试方向",
        "no_risk": "本轮无未关闭/延期缺陷，无高风险遗留。",
        "degrade_title": "辅助资料降级通知",
        "degrade_kind": "资料类型",
        "degrade_result": "解析结果",
        "degrade_action": "处置：第二节已降级为精简执行表（仅 bugStats.byModule，不推断、不占位）",
        "degrade_suggest": "建议：如需完整执行表，请提供含「测试模块 / 核心测试点 / 优先级」的标准表格",
        "key_issue_group": "方向",
        "key_issue_impact": "影响",
        "key_issue_overflow": "等 {n} 个同类缺陷",
        "list_regfail": "激活-已确认（回归不通过）",
        "list_active": "激活-待确认",
        "list_deferred": "已延期",
        "list_pending": "待回归（已解决待 QA 验证）",
        "appendix_parse": "资料解析详情",
        "appendix_conflict": "字段冲突（展示以 bugStats 为准）",
        "appendix_threshold": "生效阈值与配置",
        "appendix_source": "缺陷语义来源分布",
        "conclusion_template": (
            "本轮覆盖 {modules} 个模块，当前未关闭 {open} 个（其中回归不通过 {regfail} 个），"
            "待回归 {pending} 个，已延期 {deferred} 个，高优问题（二级及以上）{high} 个。"
        ),
        "final_conclusion": (
            "功能测试结论：缺陷总计 {total} 个，未关闭 {open} 个（含回归不通过 {regfail} 个），"
            "待回归 {pending} 个，已延期 {deferred} 个。"
        ),
        "dt_conclusion": "一、测试结论",
        "dt_metrics": "二、关键指标",
        "dt_key_issues": "三、重点问题",
        "dt_doc": "完整测试报告",
        "dt_view": "点击查看",
    },
    "en-US": {
        "report_info": "Report Info",
        "project": "Project",
        "report_kind": "Report Type",
        "coverage_period": "Coverage",
        "tester": "Tester",
        "covered_modules": "Modules",
        "generated_at": "Generated At",
        "sec_conclusion": "1. Conclusion",
        "sec_metrics": "2. Metrics Dashboard",
        "sec_key_issues": "3. Key Issues",
        "sec_coverage": "4. Functional Coverage & Execution",
        "sec_module_detail": "5. Module Detail",
        "sec_risk": "6. Risk Assessment",
        "sec_lists": "7. Open & Pending Lists",
        "sec_appendix": "8. Appendix (parsing / conflicts / thresholds)",
        "metrics_by_level": "By Severity",
        "metrics_by_status": "By Status",
        "level": "Level",
        "count": "Count",
        "status": "Status",
        "total": "Total",
        "th_module": "Module",
        "th_core": "Core Test Points",
        "th_priority": "Priority",
        "th_result": "Result",
        "th_open": "Open",
        "th_pending": "Pending",
        "th_deferred": "Deferred",
        "th_regfail": "Regression Failed",
        "th_remark": "Remark",
        "th_risk_dir": "Risk Area (Module)",
        "th_risk_level": "Risk Level",
        "th_action": "Action",
        "th_plan_area": "Mapped Area",
        "no_risk": "No open/deferred defects this round; no high risk remaining.",
        "degrade_title": "Auxiliary Material Degraded",
        "degrade_kind": "Material Type",
        "degrade_result": "Parse Result",
        "degrade_action": "Action: section degraded to simplified table (bugStats.byModule only, no inference)",
        "degrade_suggest": "Tip: provide a table with Module / Core Test Points / Priority for the full table",
        "key_issue_group": "Area",
        "key_issue_impact": "Impact",
        "key_issue_overflow": "and {n} more similar defects",
        "list_regfail": "Active-Confirmed (Regression Failed)",
        "list_active": "Active-Pending",
        "list_deferred": "Deferred",
        "list_pending": "Pending Regression (resolved, awaiting QA)",
        "appendix_parse": "Material Parsing Detail",
        "appendix_conflict": "Field Conflicts (bugStats is authoritative)",
        "appendix_threshold": "Effective Thresholds & Config",
        "appendix_source": "Defect Semantic Sources",
        "conclusion_template": (
            "Covered {modules} modules. Open {open} (regression failed {regfail}), "
            "pending {pending}, deferred {deferred}, high-priority (>= level 2) {high}."
        ),
        "final_conclusion": (
            "Functional test conclusion: total {total} defects, open {open} (incl. regression failed {regfail}), "
            "pending {pending}, deferred {deferred}."
        ),
        "dt_conclusion": "1. Conclusion",
        "dt_metrics": "2. Key Metrics",
        "dt_key_issues": "3. Key Issues",
        "dt_doc": "Full Report",
        "dt_view": "Open",
    },
}


def get_strings(locale):
    return STRINGS.get(locale, STRINGS["zh-CN"])
