#!/usr/bin/env node
/**
 * 读回归批次 → 生成 Canvas 评审面板（.canvas.tsx）。
 *
 *   node regress-canvas.mjs --batch <batch-dir>
 *
 * 面板内联 final.png（base64），点 PASS/FAIL 持久化（useCanvasState），
 * 全部标记后点「提交结论」→ newComposerChat 把结论发回 chat。
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function parseArgs() {
  const args = process.argv.slice(2);
  const out = {};
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--batch') out.batch = args[++i];
  }
  if (!out.batch) {
    console.error('用法: node regress-canvas.mjs --batch <batch-dir>');
    process.exit(1);
  }
  return out;
}

function readBatch(batchDir) {
  const abs = path.resolve(batchDir);
  const summaryPath = path.join(abs, 'batch-summary.json');
  const summary = JSON.parse(fs.readFileSync(summaryPath, 'utf8'));
  const items = (summary.succeeded || []).map((s) => {
    const bugDir = s.dir || path.join(abs, String(s.bugId));
    const tplPath = path.join(bugDir, 'template.md');
    let stepsText = '';
    if (fs.existsSync(tplPath)) {
      const md = fs.readFileSync(tplPath, 'utf8');
      const m = md.match(/## steps replayed\n([\s\S]*?)(\n## |\n##evidence|\n## evidence|$)/);
      if (m) stepsText = m[1].trim();
    }
    return {
      bugId: String(s.bugId),
      title: s.title || '',
      dir: bugDir,
      stepsText,
      finalPng: path.join(bugDir, 'final.png'),
    };
  });
  return { summary, items, batchDir: abs };
}

function imgToBase64(p) {
  if (!fs.existsSync(p)) return null;
  const buf = fs.readFileSync(p);
  return 'data:image/png;base64,' + buf.toString('base64');
}

function jstr(s) {
  return JSON.stringify(String(s == null ? '' : s));
}

function findCanvasDir() {
  const home = process.env.USERPROFILE || process.env.HOME;
  const projRoot = path.join(home, '.cursor', 'projects');
  if (!fs.existsSync(projRoot)) return null;
  const candidates = fs.readdirSync(projRoot).filter((d) =>
    d.toLowerCase().includes('skills') && d.toLowerCase().includes('desktop')
  );
  if (!candidates.length) return null;
  candidates.sort((a, b) => {
    const sa = fs.statSync(path.join(projRoot, a)).mtimeMs;
    const sb = fs.statSync(path.join(projRoot, b)).mtimeMs;
    return sb - sa;
  });
  return path.join(projRoot, candidates[0], 'canvases');
}

function generateCanvas(items, batchDir) {
  const batchName = path.basename(batchDir);
  const batchDirEsc = batchDir.replace(/\\/g, '\\\\');
  const batchDirJson = jstr(batchDir);

  // 组装 ITEMS 字面量
  const itemsLines = items.map((it) => {
    const b64 = imgToBase64(it.finalPng);
    const stepsArr = it.stepsText
      ? '[' + it.stepsText.split(/\r?\n/).map((l) => l.trim()).filter(Boolean).map(jstr).join(', ') + ']'
      : '[]';
    return [
      '  {',
      '    bugId: ' + jstr(it.bugId) + ',',
      '    title: ' + jstr(it.title) + ',',
      '    steps: ' + stepsArr + ',',
      '    img: ' + (b64 ? jstr(b64) : 'null') + ',',
      '    zentaoUrl: ' + jstr('https://zentao.pgiot.com/zentao/bug-view-' + it.bugId + '.html') + ',',
      '  }',
    ].join('\n');
  });

  // verdict 初始对象
  const verdictInit = '{ ' + items.map((it) => jstr(it.bugId) + ': null').join(', ') + ' }';

  // build mark 参数（只含已判的）
  const markParts = items
    .map((it) => '${verdicts[' + jstr(it.bugId) + '] ? `' + it.bugId + '=${verdicts[' + jstr(it.bugId) + ']}` : ""}')
    .join(' ');

  // 直接用模板字符串拼整个 tsx。注意：这是「生成代码」的生成器，可读性必然差，逐段对齐。
  const tsx = [
    '// AUTO-GENERATED by regress-canvas.mjs — do not edit by hand.',
    '// Batch: ' + batchName,
    'import { useCanvasState, useCanvasAction, Button, Card, CardHeader, CardBody, Grid, Row, Stack, Text, H1, Pill, Callout, Divider, Spacer, Link, Stat } from "cursor/canvas";',
    '',
    'interface BugItem {',
    '  bugId: string;',
    '  title: string;',
    '  steps: string[];',
    '  img: string | null;',
    '  zentaoUrl: string;',
    '}',
    '',
    'const ITEMS: BugItem[] = [',
    itemsLines.join(',\n'),
    '];',
    '',
    'type VerdictMap = { [bugId: string]: "PASS" | "FAIL" | null };',
    '',
    'function VerdictPill({ verdict }: { verdict: "PASS" | "FAIL" | null }) {',
    '  if (!verdict) return <Pill tone="neutral">未判</Pill>;',
    '  if (verdict === "PASS") return <Pill tone="success" active>PASS</Pill>;',
    '  return <Pill tone="danger" active>FAIL</Pill>;',
    '}',
    '',
    'function Thumb({ bugId, src, onOpen }: { bugId: string; src: string; onOpen: () => void }) {',
    '  return (',
    '    <Stack gap={4}>',
    '      <Text size="small" tone="tertiary">点击截图弹窗放大查看</Text>',
    '      <img',
    '        src={src}',
    '        onClick={onOpen}',
    '        style={{ width: "100%", maxHeight: 260, objectFit: "cover", borderRadius: 6, cursor: "zoom-in", display: "block", border: "1px solid rgba(128,128,128,0.3)" }}',
    '        alt={`final state of bug #${bugId} — click to zoom`} />',
    '    </Stack>',
    '  );',
    '}',
    '',
    'function Lightbox({ items, activeId, scale, onClose, onToggleZoom }: {',
    '  items: BugItem[];',
    '  activeId: string | null;',
    '  scale: number;',
    '  onClose: () => void;',
    '  onToggleZoom: () => void;',
    '}) {',
    '  if (!activeId) return null;',
    '  const item = items.find((it) => it.bugId === activeId);',
    '  if (!item || !item.img) return null;',
    '  return (',
    '    <div',
    '      onClick={onClose}',
    '      style={{',
    '        position: "fixed", inset: 0, zIndex: 50,',
    '        background: "rgba(0,0,0,0.85)",',
    '        display: "flex", alignItems: "center", justifyContent: "center",',
    '        flexDirection: "column", gap: 10, padding: 16, cursor: "zoom-out",',
    '      }}>',
    '      <div style={{ display: "flex", gap: 10, alignItems: "center", cursor: "default" }} onClick={(e: any) => e.stopPropagation()}>',
    '        <Text size="small" style={{ color: "rgba(255,255,255,0.7)" }}>#{item.bugId} · {scale === 1 ? "100%" : "200%"} · 点图切换 · 点空白关闭</Text>',
    '      </div>',
    '      <div style={{ overflow: "auto", maxWidth: "94%", maxHeight: "82%", cursor: "auto" }} onClick={(e: any) => e.stopPropagation()}>',
    '        <img',
    '          src={item.img}',
    '          onClick={onToggleZoom}',
    '          style={{ transform: `scale(${scale})`, transformOrigin: "center top", maxWidth: "100%", cursor: "zoom-in", display: "block", borderRadius: 4 }}',
    '          alt={`zoomed final state of bug #${item.bugId}`} />',
    '      </div>',
    '    </div>',
    '  );',
    '}',
    '',
    'function BugCard({ item, verdict, onSet, onOpen }: {',
    '  item: BugItem;',
    '  verdict: "PASS" | "FAIL" | null;',
    '  onSet: (v: "PASS" | "FAIL") => void;',
    '  onOpen: (bugId: string) => void;',
    '}) {',
    '  return (',
    '    <Card size="lg">',
    '      <CardHeader trailing={<VerdictPill verdict={verdict} />}>',
    '        #{item.bugId} · {item.title.slice(0, 40)}',
    '      </CardHeader>',
    '      <CardBody>',
    '        <Stack gap={10}>',
    '          {item.img ? (',
    '            <Thumb bugId={item.bugId} src={item.img} onOpen={() => onOpen(item.bugId)} />',
    '          ) : (',
    '            <Callout tone="warning" title="无 final.png">该 bug 缺少回放终态截图</Callout>',
    '          )}',
    '',
    '          <details>',
    '            <summary style={{ cursor: "pointer", color: "inherit", opacity: 0.7, fontSize: 12 }}>回放步骤（{item.steps.length}）</summary>',
    '            <Stack gap={2} style={{ marginTop: 6 }}>',
    '              {item.steps.map((s, i) => (<Text key={i} size="small" tone="tertiary">{s}</Text>))}',
    '            </Stack>',
    '          </details>',
    '',
    '          <Divider />',
    '          <Row gap={8} align="center">',
    '            <Button variant={verdict === "PASS" ? "primary" : "secondary"} onClick={() => onSet("PASS")}>PASS</Button>',
    '            <Button variant={verdict === "FAIL" ? "primary" : "secondary"} onClick={() => onSet("FAIL")}>FAIL</Button>',
    '            <Spacer />',
    '            <Link href={item.zentaoUrl}>禅道</Link>',
    '          </Row>',
    '        </Stack>',
    '      </CardBody>',
    '    </Card>',
    '  );',
    '}',
    '',
    'export default function RegressionReview() {',
    '  const [verdicts, setVerdicts] = useCanvasState<VerdictMap>("verdicts", ' + verdictInit + ');',
    '  const [lightboxId, setLightboxId] = useCanvasState<string | null>("lightbox-active", null);',
    '  const [lightboxScale, setLightboxScale] = useCanvasState<number>("lightbox-scale", 1);',
    '  const dispatch = useCanvasAction();',
    '',
    '  const setOne = (bugId: string, v: "PASS" | "FAIL") => {',
    '    setVerdicts((prev) => ({ ...prev, [bugId]: prev[bugId] === v ? null : v }));',
    '  };',
    '',
    '  const openLightbox = (bugId: string) => {',
    '    setLightboxScale(1);',
    '    setLightboxId(bugId);',
    '  };',
    '  const closeLightbox = () => setLightboxId(null);',
    '  const toggleZoom = () => setLightboxScale(lightboxScale === 1 ? 2 : 1);',
    '',
    '  const entries = ITEMS.map((it) => verdicts[it.bugId]);',
    '  const passN = entries.filter((v) => v === "PASS").length;',
    '  const failN = entries.filter((v) => v === "FAIL").length;',
    '  const pendingN = ITEMS.length - passN - failN;',
    '',
    '  const handleSubmit = () => {',
    '    const parts = ITEMS.map((it) => `${it.bugId}=${verdicts[it.bugId] || "未判"}`);',
    '    const markArgs = ITEMS.filter((it) => verdicts[it.bugId]).map((it) => `${it.bugId}=${verdicts[it.bugId]}`).join(" ");',
    '    const prompt = [',
    '      "请按以下结论执行回归提交：",',
    '      ...parts,',
    '      `1) node scripts/regress-mark.mjs --batch ' + batchDirJson.replace(/"/g, '\\"') + ' --set ${markArgs}`,',
    '      `2) node scripts/regress-submit.mjs --batch ' + batchDirJson.replace(/"/g, '\\"') + ' --yes`,',
    '    ].join("\\n");',
    '    dispatch({ type: "newComposerChat", userPrompt: prompt });',
    '  };',
    '',
    '  return (',
    '    <Stack gap={16}>',
    '      <H1>回归评审 · ' + batchName + '</H1>',
    '',
    '      <Row gap={16}>',
    '        <Stat value={String(ITEMS.length)} label="总数" />',
    '        <Stat value={String(passN)} label="PASS" tone="success" />',
    '        <Stat value={String(failN)} label="FAIL" tone="danger" />',
    '        <Stat value={String(pendingN)} label="待判" tone="warning" />',
    '      </Row>',
    '',
    '      <Divider />',
    '',
    '      <Grid columns={2} gap={16}>',
    '        {ITEMS.map((it) => (',
    '          <BugCard key={it.bugId} item={it} verdict={verdicts[it.bugId]} onSet={(v) => setOne(it.bugId, v)} onOpen={openLightbox} />',
    '        ))}',
    '      </Grid>',
    '',
    '      <Divider />',
    '',
    '      <Row gap={12} align="center">',
    '        <Button variant="primary" onClick={handleSubmit}>',
    '          提交结论（{passN + failN}/{ITEMS.length}）',
    '        </Button>',
    '        <Text tone="tertiary" size="small">{pendingN > 0 ? `还有 ${pendingN} 条未标记` : "全部已标记，可提交"}</Text>',
    '      </Row>',
    '',
    '      <Callout tone="info" title="流程">',
    '        逐张点 PASS / FAIL（状态自动持久化）→ 全部标记后点「提交结论」→ 聊天会收到带 mark + submit 命令的消息，我据此执行。',
    '      </Callout>',
    '',
    '      <Lightbox',
    '        items={ITEMS}',
    '        activeId={lightboxId}',
    '        scale={lightboxScale}',
    '        onClose={closeLightbox}',
    '        onToggleZoom={toggleZoom} />',
    '    </Stack>',
    '  );',
    '}',
  ].join('\n');

  return tsx;
}

function main() {
  const { batch } = parseArgs();
  const { items, batchDir } = readBatch(batch);
  if (!items.length) {
    console.error('批次目录无 succeeded 条目');
    process.exit(1);
  }

  const code = generateCanvas(items, batchDir);
  const canvasDir = findCanvasDir();
  if (!canvasDir) {
    console.error('找不到 Cursor canvases 目录');
    process.exit(1);
  }
  fs.mkdirSync(canvasDir, { recursive: true });
  const outPath = path.join(canvasDir, 'regression-review.canvas.tsx');
  fs.writeFileSync(outPath, code, 'utf8');

  const kb = Math.round(fs.statSync(outPath).size / 1024);
  console.log('[canvas] 生成 ' + items.length + ' 条 bug 面板 -> ' + outPath + ' (' + kb + ' KB)');
  console.log('[canvas] 批次：' + batchDir);
  console.log('[canvas] 打开面板后：点每张卡 PASS/FAIL -> 点「提交结论」');
}

main();
